import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {blankDocument,today} from '../src/domain/invoice.js';
const userA='11111111-1111-4111-8111-111111111111', userB='22222222-2222-4222-8222-222222222222';
test('cloud SQL enforces ownership, mutations, concurrency, imports and file privacy',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth,storage to authenticated,anon; grant execute on function auth.uid() to authenticated,anon; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,primary key(bucket_id,name)); alter table storage.objects enable row level security; grant select,insert,update,delete on storage.objects to authenticated; create function storage.foldername(name text) returns text[] language sql immutable as $$ select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1] $$; insert into auth.users values('${userA}'),('${userB}');`);
 await db.exec(await readFile('supabase/migrations/202609070001_cloud_records.sql','utf8'));
 const asUser=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const rpc=async(name,args)=>{const params=args.map((_,i)=>'$'+(i+1)).join(',');return(await db.query(`select public.${name}(${params}) as result`,args.map(a=>typeof a==='object'?JSON.stringify(a):a))).rows[0].result;};
 await asUser(userA);
 let d=await rpc('ha_create',[blankDocument('pending')]);assert.equal(d.number,'HA-0001');
 const retried=await rpc('ha_create',[{...d,number:'ignored'}]);assert.equal(retried.id,d.id);
 await assert.rejects(db.query('update public.ha_documents set number=$1',['bad']),/permission denied/);
 d.customerName='Private client';d=await rpc('ha_save',[d,'issue',{}]);assert.equal(d.status,'Issued');
 const stale=structuredClone(d);d.notes='Correction';d=await rpc('ha_save',[d,'save',{}]);
 await assert.rejects(rpc('ha_save',[stale,'save',{}]),/another device/);
 await asUser(userB);assert.equal((await db.query('select * from public.ha_documents')).rows.length,0);
 await assert.rejects(rpc('ha_save',[d,'save',{}]),/not found/);
 const b=await rpc('ha_create',[blankDocument('pending')]);assert.equal(b.number,'HA-0001');
 await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['high-amps-attachments',`${userA}/${d.id}/${crypto.randomUUID()}`]),/row-level security/);
 await asUser(userA);
 const fileId=crypto.randomUUID(), path=`${userA}/${d.id}/${fileId}`;
 await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['high-amps-attachments',path]);
 d.attachments=[{id:fileId,name:'Receipt',showOnInvoice:true}];d=await rpc('ha_save',[d,'save',{}]);
 d=await rpc('ha_save',[d,'paid',{paidDate:today(),paymentMethod:'Zelle'}]);assert.equal(d.status,'Paid');
 await assert.rejects(rpc('ha_save',[{...d,status:'Draft'},'save',{}]),/locked/);
 assert.equal(await rpc('ha_import',[{...d,status:'Draft'},[],[]]),false);
 await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['high-amps-attachments',`${userA}/${d.id}/${crypto.randomUUID()}`]),/row-level security/);
 assert.equal((await db.query('delete from storage.objects where name=$1 returning name',[path])).rows.length,0);
 await asUser(userB);assert.equal((await db.query('select * from storage.objects where name=$1',[path])).rows.length,0);
 assert.equal((await db.query('select * from public.ha_files')).rows.length,0);
 assert.equal((await db.query('select * from public.ha_revisions')).rows.length,0);
 await db.exec('reset role');await db.exec('set role anon');
 await assert.rejects(rpc('ha_create',[blankDocument('pending')]),/permission denied/);
 await db.close();
});
